###
GET {{host}}/swagger

###
GET {{host}}/swagger/tutorials

###
GET {{host}}/swagger/tutorials/232

###
POST {{host}}/swagger/tutorials
Content-Type: application/json

{
  "id": 0,
  "name": "小明",
  "email": "pt@outlook.com"
}
