###
GET http://localhost:8942/cats
Accept: application/json

###
GET http://localhost:8942/cats/哈哈
Accept: application/json

###
POST http://localhost:8942/cats
Content-Type: application/json

{
  "data": {
    "case_type": "C"
  }
}

###
DELETE http://localhost:8942/cats
Accept: application/json

###
PUT http://localhost:8942/cats
Content-Type: application/json

{
  "name": "1",
  "age": 1,
  "breed": "liang"
}