###
GET http://localhost:8942/cats
Accept: application/json

###
GET http://localhost:8942/cats/1
Accept: application/json

###
POST http://localhost:8942/cats
Content-Type: application/json

{
  "data": {
    "case_type": "C"
  }
}

###
DELETE http://localhost:8942/cats
Accept: application/json

###
PUT http://localhost:8942/cats
Content-Type: application/json

{
  "name": "1",
  "age": 1,
  "breed": "liang"
}
###
POST http://localhost:8942/cats/add
Content-Type: application/json

{
  "k": "k1",
  "s": "s1"
}

### 授权
POST http://localhost:8942/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "changeme"
}

### 授权
GET http://localhost:8942/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDkyMzA0NDQsImV4cCI6MTYwOTIzMDUwNH0.9XlExcwRg8jDyEOdvD6OAINOQ-uuzTF5w8DhnVsDVB4


### 重定向
GET http://localhost:8942/wx-redirect-uri?code=2&url=https%3A%2F%2Fbaidu.com

